#!/usr/bin/env bash

# DotFiles Linker

# requirements:
# - bash, I guess
# - readlink

# optionals:
# - git

# https://stackoverflow.com/a/246128/1407614
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

script_name="dfl"
script_url="https://raw.githubusercontent.com/mapperr/dfl/master/dfl"

dotfiles_dir="dotfiles"
default_profile_name="default"
secrets_profile_name="secrets"
track_filename=".track"
target_directory="$HOME"
debug="false"

dfl_user_dir_name=".dfl"
dfl_user_dir_abs="$HOME/$dfl_user_dir_name"
dotfiles_dir_abs="$dfl_user_dir_abs/$dotfiles_dir"
track_file_abs="$dfl_user_dir_abs/$track_filename"
untrack_file_abs="$dfl_user_dir_abs/.untrack"

update_scriptpath_abs="$dfl_user_dir_abs/update_dfl.sh"
backup_suffix="-dflbak"

logd() {
    local msg="$1"
    test "$debug" = "true" && echo "$msg"
}

write_update_script() {
    cat > "$update_scriptpath_abs" << EOF
#!/bin/bash
script_path_abs="$SCRIPT_DIR/$script_name"
if hash curl; then
    curl -o "\$script_path_abs" "$script_url"
    if [ \$? -ne 0 ]; then
        echo "ERROR: cannot update myself"
        exit 1
    fi
fi
echo "Updated"
EOF
}

take_file() {
    local file="$1"
    local profile="$2"

    local current_dir_abs=`pwd`

    if [ -z "$profile" ]; then
        local profile="$default_profile_name"
    fi

    if [ -L "$file" ]; then
        echo "[$file] is already a symlink, just take/move the original file" >&2
        return 1
    fi

    if [ ! -f "$file" ] && [ ! -d "$file" ]; then
        echo "[$file] is not a regular file/directory" >&2
        return 1
    fi

    if echo "$file" | grep -e "^/" -e "^~/" >/dev/null; then
        local filepath_abs="$file"
    else
        local filepath_abs="$current_dir_abs/$file"
    fi

    if ! echo "$filepath_abs" | grep "^$target_directory" >/dev/null; then
        echo "ERROR: [$filepath_abs] is not in [$target_directory]"
        return 1
    fi

    local target_relative_filepath=`echo "$filepath_abs" | sed "s#^$target_directory/##"`
    logd "target-relative filepath: [$target_relative_filepath]"

    if ! echo "$target_relative_filepath" | grep '^\.' >/dev/null; then
        echo "ERROR: [$file] is not a dotfile nor in a dotdirectory"
        return 1
    fi

    local target_relative_filepath_undotted=`echo "$target_relative_filepath" | sed 's#^\.##'`
    local profile_filepath_abs="$dotfiles_dir_abs/$profile/$target_relative_filepath_undotted"

    local profile_dir_path_abs=`dirname "$profile_filepath_abs"`

    echo -n "taking [$filepath_abs] into $profile profile as [$target_relative_filepath_undotted]... "
    test -d "$profile_dir_path_abs" || mkdir -p "$profile_dir_path_abs"
    mv "$filepath_abs" "$profile_filepath_abs"
    echo "done."
}

track_file() {
    local file_to_track="$1"
    if ! grep $file_to_track $track_file_abs >/dev/null; then
        echo "$file_to_track" >> $track_file_abs
    fi
}

process_file() {
    local profile_name="$1"
    local relative_filepath="$2"

    local absolute_source_path="$dotfiles_dir_abs/$profile_name/$relative_filepath"
    local target_filepath="$target_directory/.$relative_filepath"
    local target_dirname=`dirname $target_filepath`

    if [ ! -d "$target_dirname" ]; then
        logd "creating directory [$target_dirname]"
        mkdir -p $target_dirname
    fi

    if [ -f "$target_filepath" ] || [ -L "$target_filepath" ]; then
        logd "[$target_filepath] exists"
        if readlink "$target_filepath" > /dev/null; then
            logd "deleting existing link [$target_filepath]"
            rm -f $target_filepath
        else
            echo "WARNING: [$target_filepath] is present and is not a link"
            echo -n "do you want to replace it with a link? (I'll backup it as [$target_filepath$backup_suffix]) (y/n) "
            read c
            if [ "$c" = "y" ]; then
                mv $target_filepath $target_filepath$backup_suffix
                if [ ! $? = 0 ]; then
                    echo "ERROR: cannot backup [$target_filepath], I will not link it"
                    return
                fi
            else
                echo "ok, I wont touch it"
                return
            fi
        fi
    else
        logd "[$target_filepath] does not exists, I will link it"
    fi

    echo -n "linking [$absolute_source_path] to [$target_filepath]... "
    ln -s $absolute_source_path $target_filepath
    track_file $target_filepath
    echo "done."
}

process_deleted_files() {
    local profile_dir="$1"

    test -f "$untrack_file_abs" && rm -f "$untrack_file_abs"

    for tracked_file in `cat $track_file_abs`; do
        logd "processing tracked file [$tracked_file]"
        local tracked_file_relative=`echo "$tracked_file" | sed "s_$target_directory/\.__"`
        local found="false"
        for directory in "$default_profile_name" "$secrets_profile_name" "$profile_dir"; do
            test -z "$directory" && continue
            local directory_abs="$dotfiles_dir_abs/$directory"
            test ! -d $directory_abs && continue
            local filepath="$directory_abs/$tracked_file_relative"
            logd "checking if file [$filepath] exists"
            if [ -f "$filepath" ]; then
                logd "found [$filepath]"
                found="true"
                continue
            fi
        done
        if [ "$found" = "false" ]; then
            echo "deleting link [$tracked_file]"
            rm -f "$tracked_file"
            echo "$tracked_file" >> "$untrack_file_abs"
        fi
    done

    if [ -f "$untrack_file_abs" ]; then
        grep -vf "$untrack_file_abs" "$track_file_abs" > "$track_file_abs~"
        mv "$track_file_abs~" "$track_file_abs"
        rm -f "$untrack_file_abs"
    fi
}

process_subdirectory() {
    local profile_name="$1"
    local directory="$2"

    if [ -z "$directory" ]; then
        echo "argument directory is blank" >&2
        exit 1
    fi

    logd "processing subdirectory $directory"

    local relative_path="$profile_name/$directory"

    for item in `/bin/ls -A $relative_path`; do
        local item_path="$relative_path/$item"
        logd "processing item [$item_path]"

        if [ -d "$item_path" ]; then
            logd "$item is a directory"
            process_subdirectory "$profile_name" "$directory/$item"
        fi

        if [ -f "$item_path" ]; then
            process_file $profile_name $directory/$item
        fi
    done
}

process_profile() {
    local profile_name="$1"

    if [ -z "$profile_name" ]; then
        echo "argument profile_name is blank" >&2
        exit 1
    fi

    logd "processing directory $profile_name"

    for item in `/bin/ls -A $profile_name`; do

        if [ -d "$profile_name/$item" ]; then
            logd "$item is a directory"
            process_subdirectory "$profile_name" "$item"
        fi

        if [ -f "$profile_name/$item" ]; then
            process_file $profile_name $item
        fi
    done
}

helpmsg() {
    echo "Usage: `basename $0` [-v] <command>
    Commands:
        l, link [profile_name]
            links dotfiles in default, secrets and, eventually, profile_name directories, in this order

        t, take filename|dirname [profile_name]
            move the file (or directory) into your dotfiles, in the specified profile directory, or in default if its omitted

        g, git [git_arguments]
            runs git commands in the dotfiles directory

        clone <git repository>
            clone a git repo in the dotfile directory, backupping the eventual existing one

        d
            prints the dotfiles directory absolute path

        u, up, update
            self update from [$script_url]

    Options:
        -v  -  activate verbose mode
"
}

# -------

if [ ! -d "$dfl_user_dir_abs" ]; then
    mkdir -p "$dfl_user_dir_abs"
fi

command="$1"

if [ "$command" = "-v" ]; then
    debug=true
    shift
    command="$1"
fi


if [ "$command" = "g" ] || [ "$command" = "git" ]; then

    shift
    if [ ! -d $dotfiles_dir_abs ]; then
        echo "I cannot find the dotfiles directory [$dotfiles_dir_abs]"
        echo "You can clone your dotfiles repo with 'dfl clone'"
        echo "or copy some dotfiles in [$dotfiles_dir_abs/default]"
        exit 1
    fi
    cd $dotfiles_dir_abs > /dev/null
    git $@
    cd - >/dev/null

elif [ "$command" = "cd" ] || [ "$command" = "j" ]; then

    cd "$dotfiles_dir_abs"

elif [ "$command" = "d" ]; then

    echo "$dotfiles_dir_abs"

elif [ "$command" = "clone" ]; then

    shift
    repo="$1"
    if [ -d "$dotfiles_dir_abs" ]; then
        echo -n "Backupping dotfiles current dir... "
        mv $dotfiles_dir_abs $dotfiles_dir_abs$backup_suffix
        if [ $? -ne 0 ]; then
            echo "ERROR: Cannot backup $directory_abs, aborting" >&2
            exit 1
        fi
        echo "done."
    fi
    cd $dfl_user_dir_abs >/dev/null
    dotfiles_cloned_dir="dotfiles-cloned"
    git clone "$repo" $dotfiles_cloned_dir
    if [ $? -ne 0 ]; then
        echo "ERROR: Cannot clone repo [$repo], rollbacking" >&2
        rm -rf $dotfiles_cloned_dir
        mv $dotfiles_dir_abs$backup_suffix $dotfiles_dir_abs
        exit 1
    fi
    mv $dotfiles_cloned_dir $dotfiles_dir
    cd - >/dev/null

elif [ "$command" = "t" ] || [ "$command" = "take" ]; then

    shift
    file="$1"
    profile="$2"
    take_file "$file" "$profile"

elif [ "$command" = "l" ] || [ "$command" = "link" ]; then

    shift
    profile="$1"
    if [ ! -d $dotfiles_dir_abs ]; then
        echo "I cannot find the dotfiles directory [$dotfiles_dir_abs]"
        echo "You can clone your dotfiles repo with 'dfl clone'"
        echo "or copy some dotfiles in [$dotfiles_dir_abs/default]"
        exit 1
    fi
    cd $dotfiles_dir_abs > /dev/null
    test -d $default_profile_name && process_profile $default_profile_name
    if [ ! -z "$profile" ]; then
        test -d $profile && process_profile $profile
    fi
    test -d $secrets_profile_name && process_profile $secrets_profile_name
    cd - >/dev/null
    process_deleted_files $profile

elif [ "$command" = "u" ] || [ "$command" = "up" ] || [ "$command" = "update" ]; then

    write_update_script
    exec /bin/bash "$update_scriptpath_abs"

else
    helpmsg
fi

